<?php
namespace Extasy\Users\Columns;

use \Extasy\Model\Columns\Input;
use \Faid\View\View;
use \InvalidArgumentException;

class Email extends Input
{
    const RegExp = '/.+@.+\..+/i';

    public function validate( $email ) {
        if ( empty( $email )) {
            return ;
        }
        if ( !preg_match( self::RegExp, $email )) {
            throw new InvalidArgumentException(sprintf('Not an Email:%s', $email));
        }
    }
    public function setValue($newValue)
    {
        $this->validate( $newValue );
        parent::setValue($newValue); // TODO: Change the autogenerated stub
    }

    public function getAdminFormValue()
    {
        $view = new View(__DIR__ . '/email.tpl');
        $view->set('name', $this->fieldName);
        $view->set('value', $this->value);

        return $view->render();
    }
} 